### ISSUE TITLE
Consolidate 2 functions in benchmarkScore.fsx

### ISSUE THREAD

**Issue by jamessdixon** [jamessdixon/Kaggle.HomeDepot#2]
trainInput and testInput are almost identical.  They can be consolidated into a single function

**Comment by taylorwood** [comment]
I took a quick stab at this, but I'm not sure how to define a function that works with the CSV type provider's generated row type.

**Comment by jamessdixon** [comment]
Did you submit a pull request?

**Comment by taylorwood** [comment]
Nope, couldn't figure out how to define a function that takes the generated CSV type or if that's even possible. I guess we could map those values to a tuple/record, maybe not worth it.

**Comment by jamessdixon** [comment]
Perhaps I wasn't thinking clearly when I thought of this.  I'll take a look and consolidate.  Right now, I am neck deep in Python port...

**Comment by tjaskula** [comment]
Don't forget to push the card in trello to done :) With the comment that it's not done :)
